### ISSUE TITLE
Font files fail to load after passing through the proxy

### ISSUE THREAD

**Issue by abhinavsayan** [IRus/kotlin-dev-proxy#2]
I tried setting the individual content tpe for these files but I still get the error 
OTS parsing error: Failed to convert WOFF 2.0 font to SFNT

**Comment by IRus** [comment]
@abhinavsayan Thanks for report, I'll look into that today!

**Comment by abhinavsayan** [comment]
@IRus I created an exact same version in Java over spark. The issue was with all binary files. 
I have fixed it in java project. I'll send over the fix.

**Comment by abhinavsayan** [comment]
You can find the fix [here](https://github.com/abhinavsayan/java-spark-proxy-server/blob/master/SparkProxy.java).

The response is copied as a binary stream rather than a text result. I'll upload the whole project soon.

**Comment by IRus** [comment]
Fixed after migrating to undertow.
